### PR TITLE
Fix/non invertible matrix

### LINKED ISSUE #23: Trying to run two process
image

### PR DESCRIPTION
**Pull request by pevab**
Closes #23

### CODE REVIEW

File: src/main/kotlin/ch/kleis/lcaplugin/compute/matrix/impl/ojalgo/OjalgoSolver.kt [hunk 1]
```diff
@@ -2,11 +2,12 @@ package ch.kleis.lcaplugin.compute.matrix.impl.ojalgo
 
 import ch.kleis.lcaplugin.compute.matrix.impl.Matrix
 import ch.kleis.lcaplugin.compute.matrix.impl.Solver
+import org.ojalgo.RecoverableCondition
 
 import org.ojalgo.matrix.task.SolverTask;
```
Comment (sebdebros) [inline src/main/kotlin/ch/kleis/lcaplugin/compute/matrix/impl/ojalgo/OjalgoSolver.kt:7]: semi-column to be removed

File: src/main/kotlin/ch/kleis/lcaplugin/compute/matrix/impl/ojalgo/OjalgoSolver.kt [hunk 2]
```diff
@@ -2,11 +2,12 @@ package ch.kleis.lcaplugin.compute.matrix.impl.ojalgo
...
 
 class OjalgoSolver : Solver {
-    override fun solve(lhs: Matrix, rhs: Matrix): Matrix {
+    override fun solve(lhs: Matrix, rhs: Matrix): Matrix? {
         val a = lhs as OjalgoMatrix
         val b = rhs as OjalgoMatrix
         if (a.rowDim() == 0) {
```
Comment (sebdebros) [inline src/main/kotlin/ch/kleis/lcaplugin/compute/matrix/impl/ojalgo/OjalgoSolver.kt:13]: pourquoi deux if?
```suggestion
        if (a.rowDim() == 0 || b.colDim() == 0) {
            return OjalgoMatrixFactory().zero(a.rowDim(), b.colDim())
        }
```

File: src/main/kotlin/ch/kleis/lcaplugin/ui/toolwindow/LcaResult.kt [hunk 3]
```diff
@@ -1,27 +1,44 @@
 package ch.kleis.lcaplugin.ui.toolwindow
 
+import ch.kleis.lcaplugin.compute.matrix.InventoryError
 import ch.kleis.lcaplugin.compute.matrix.InventoryMatrix
+import ch.kleis.lcaplugin.compute.matrix.InventoryResult
+import com.intellij.ui.components.JBLabel
 import com.intellij.ui.components.JBScrollPane
 import com.intellij.ui.table.JBTable
 import com.intellij.util.ui.JBEmptyBorder
+import com.intellij.util.ui.UIUtil
```
Comment (sebdebros) [inline src/main/kotlin/ch/kleis/lcaplugin/ui/toolwindow/LcaResult.kt:10]: unused imports

**Review by sebdebros — APPROVED** [review]
